export const dataHeader = [
  "Firstname",
  "Lastname",
  "Start",
  "Department",
  "Birth",
  "Street",
  "City",
  "State",
  "ZipCode",
];

export const tableItem = [
  {
    firstname: "jimmy",
    lastname: "Lelievre",
    start: "02/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "berber",
    lastname: "ala",
    start: "13/03/2010",
    department: "Sales",
    birth: "01/02/2001",
    street: "20 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "anna",
    lastname: "Bernard",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "20100",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "bernard",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "3200",
  },
  {
    firstname: "luc",
    lastname: "Lelievre",
    start: "04/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "75000",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Gael",
    lastname: "breton",
    start: "13/03/2010",
    department: "Marketing",
    birth: "04/01/2001",
    street: "55 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Jimmy",
    lastname: "Lelievre",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "244 rue du du four",
    city: "dublin",
    state: "Alabama",
    zipcode: "42100",
  },
  {
    firstname: "Jean",
    lastname: "jacque",
    start: "13/03/2010",
    department: "Sales",
    birth: "04/01/2001",
    street: "20 rue du du four",
    city: "paris",
    state: "Alabama",
    zipcode: "42100",
  },
];
