export const dataHeader = [
  "Name",
  "Date of birth",
  "Adress",
  "Start Day",
  "Department",
];

export const tableItem = [
  {
    city: "paris",
    dateOfBirth: "04/01/2001",
    department: "Sales",
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    state: "Alabama",
    street: "244 rue du du four",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
  {
    city: "paris",
    dateOfBirth: "04/01/1991",
    department: "Sales",
    firstName: "Jean",
    lastName: "Mo",
    startDay: "13 janvier 2010",
    state: "Alabama",
    street: "244 rue du code",
    zipCode: "42100",
  },
];
